baseurl = "/"
title = "Jinyi Hung"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = "jinyihung"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"


[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publication/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/static/Hung_CV.3.2018.pdf/"
    weight = 4
[[menu.main]]
    name = "Resources"
    url = "/resource/"
    weight = 5


[params]
    description = "Jinyi Hung"
    subtitle = "test website"
    googleAnalytics = ""
    disqus = ""
    custom_css = ["/css/style.css"]



    GithubEdit = "https://github.com/rbind/njtierney.com/edit/master/content/"
    footer = "&copy; [Jinyi Hung](https://jinyihung.netlify.com) 2018 | [Github](https://github.com/jinyihung) | [Twitter](https://twitter.com/JinyiHung)"